# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: muzzle-bibfile
        name: Sanitize BibTeX files
        language: system
        types: [text]
        files: 'bib/.*\.bib'
        entry: muzzle-bibfile
      - id: isort
        name: Sort Python imports
        language: python
        entry: isort
        types: [python]
      - id: black
        name: Format Python files
        language: python
        entry: black
        types: [python]
      - id: flake8
        name: Lint Python files
        language: python
        entry: flake8
        types: [python]
        require_serial: true
